alias @gv='gvim'
alias @v='vim'
alias @p='python'
alias @ip='ipython'
alias @da='django-admin.py'
alias @pm='python manage.py'
alias @wo='workon'
alias @de='deactive'
alias @ct='tdaemon --custom-args="--verbosity=2 --rednose --force-color"'
alias @ctd='tdaemon --test-program=django --custom-args="--rednose --force-color"'
